# EDA(Exploratory Data Analysis)

In [78]:
import pandas as pd 
df=pd.read_csv("data_clean(1).csv")
df.head()

   Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1   41.0    190.0   7.4     67     5    1  2010    67       S
1           2   36.0    118.0   8.0     72     5    2  2010    72       C
2           3   12.0    149.0  12.6     74     5    3  2010    74      PS
3           4   18.0    313.0  11.5     62     5    4  2010    62       S
4           5    NaN      NaN  14.3     56     5    5  2010    56       S

In [79]:
df.info()
data_backup=df
df.shape

<class 'pandas.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  158 non-null    int64
 1   Ozone       120 non-null    float64
 2   Solar.R     151 non-null    float64
 3   Wind        158 non-null    float64
 4   Temp C      158 non-null    str
 5   Month       158 non-null    str
 6   Day         158 non-null    int64
 7   Year        158 non-null    int64
 8   Temp        158 non-null    int64
 9   Weather     155 non-null    str
dtypes: float64(3), int64(4), str(3)
memory usage: 13.2 KB

(158, 10)

In [80]:
df.describe()

       Unnamed: 0       Ozone     Solar.R  ...         Day    Year        Temp
count  158.000000  120.000000  151.000000  ...  158.000000   158.0  158.000000
mean    79.500000   41.583333  185.403974  ...   16.006329  2010.0   77.727848
std     45.754781   32.620709   88.723103  ...    8.997166     0.0    9.377877
min      1.000000    1.000000    7.000000  ...    1.000000  2010.0   56.000000
25%     40.250000   18.000000  119.000000  ...    8.000000  2010.0   72.000000
50%     79.500000   30.500000  197.000000  ...   16.000000  2010.0   78.500000
75%    118.750000   61.500000  257.000000  ...   24.000000  2010.0   84.000000
max    158.000000  168.000000  334.000000  ...   31.000000  2010.0   97.000000

[8 rows x 7 columns]

In [81]:
df.head()

   Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1   41.0    190.0   7.4     67     5    1  2010    67       S
1           2   36.0    118.0   8.0     72     5    2  2010    72       C
2           3   12.0    149.0  12.6     74     5    3  2010    74      PS
3           4   18.0    313.0  11.5     62     5    4  2010    62       S
4           5    NaN      NaN  14.3     56     5    5  2010    56       S

In [82]:
df.tail()

     Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
153         154   41.0    190.0   7.4     67     5    1  2010    67       C
154         155   30.0    193.0   6.9     70     9   26  2010    70      PS
155         156    NaN    145.0  13.2     77     9   27  2010    77       S
156         157   14.0    191.0  14.3     75     9   28  2010    75       S
157         158   18.0    131.0   8.0     76     9   29  2010    76       C

### Some datasets may have wrong values,like here month is stribg instead of numeric and this will give erroe in ml

In [83]:
df['Month']=pd.to_numeric(df['Month'])

ValueError: Unable to parse string "May" at position 23

In [ ]:
df.head(25)

In [ ]:
df['Month']=df['Month'].replace('May',5)
df.head(25)

In [ ]:
df.info()

In [ ]:
df['Month']=pd.to_numeric(df['Month'],errors='coerce')##convert unwanted values to na
df['Temp C']=pd.to_numeric(df['Temp C'],errors='coerce')
df['Weather']=df['Weather'].astype("category")

In [ ]:
df.info()

In [ ]:
df.duplicated()
df=df.drop_duplicates()
data_backup2=df

In [ ]:
df.head()

In [ ]:
df=df.drop('Unnamed: 0',axis=1)
df.head()

In [ ]:
df=df.drop('Temp C',axis=1)
df.head()

### RENAMING OF COLUMN

In [ ]:
df=df.rename({'Solar.R':'Solar'},axis=1)
df.head()

### Handling Missing Values but its different now

In [ ]:
cols=df.columns
cols

In [ ]:
import seaborn as sns
colors=['blue','red']
sns.heatmap(df[cols].isnull(),cmap=sns.color_palette(colors))

In [ ]:
df.isnull().sum()

### MEAN --- When normal distribution and no outliea 
### medain---skew and outliers
### mode---for categorical data

In [ ]:
import matplotlib.pyplot as plt
plt.figure(figsize=(8,5))
sns.boxplot(y=df['Ozone'])
plt.title("Finding Ozone outlier")

In [ ]:
## Inter quantile range 
Q1=df['Ozone'].quantile(0.25)
Q3=df['Ozone'].quantile(0.75)
IQR=Q3-Q1
lower_bound=Q1 - 1.5 * IQR
upper_bound=Q3 + 1.5 * IQR
## Finding Outlier
outlier=df[(df['Ozone']<lower_bound)|(df['Ozone']>upper_bound)]
print("Number of outliers in Ozone cloumn:- ",outlier.shape)

## Now ozone column should be filled with median

In [ ]:
ozone_medain=df['Ozone'].median()
df.fillna({'Ozone':ozone_medain},inplace=True)

In [ ]:
plt.figure(figsize=(8,5))
sns.boxplot(y=df['Solar'])
plt.title("Finding Solar outlier")

In [ ]:
solar_mean=df['Solar'].mean()
df.fillna({'Solar':solar_mean},inplace=True)

In [ ]:
weather_mode=df['Weather'].mode()[0]
df.fillna({'Weather':weather_mode},inplace=True)

In [ ]:
df.isna().sum()

In [ ]:
sns.boxplot(df)

In [ ]:
## Inter quantile range 
Q1=df['Wind'].quantile(0.25)
Q3=df['Wind'].quantile(0.75)
IQR=Q3-Q1
lower_bound=Q1 - 1.5 * IQR
upper_bound=Q3 + 1.5 * IQR
## Finding Outlier
outlier=df[(df['Wind']<lower_bound)|(df['Wind']>upper_bound)]
print("Number of outliers in Wind cloumn:- ",outlier.shape[0])

In [ ]:
wind_median=df['Wind'].median()
wind_median

In [ ]:
df.loc[df['Wind']<lower_bound,'Wind']=wind_medain
df.loc[df['Wind']>upper_bound,'Wind']=wind_medain

In [ ]:
plt.figure(figsize=(8,5))
sns.boxplot(df['Wind'])

In [ ]:
outlier=df[(df['Wind']<lower_bound)|(df['Wind']>upper_bound)]
print("Number of outliers in Wind cloumn:- ",outlier.shape[0])

In [85]:
## For Ozone
Q1=df['Ozone'].quantile(0.25)
Q3=df['Ozone'].quantile(0.75)
##IQR
IQR=Q3-Q1
lower_bound=Q1 - 1.5 *IQR
upper_bound=Q3 + 1.5 *IQR

outlier=df[(df['Ozone']<lower_bound)|(df['Ozone']>upper_bound)]
print("Number of outliers in Ozone cloumn:- ",outlier.shape[0])

Number of outliers in Ozone cloumn:-  2

In [86]:
ozone_medain_1=df['Ozone'].median()
df.loc[df['Ozone']<lower_bound,'Ozone']=ozone_medain_1
df.loc[df['Ozone']>upper_bound,'Ozone']=ozone_medain_1
outlier=df[(df['Ozone']<lower_bound)|(df['Ozone']>upper_bound)]
print("Number of outliers in Ozone cloumn:- ",outlier.shape[0])

Number of outliers in Ozone cloumn:-  0

In [ ]:
##df=pd.get_dummies(df,['Weather'])

In [ ]:
df.head()

In [87]:
# df=pd.get_dummies(df,columns=['Weather']).astype(int)
# df.head()

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer.Replace or remove non-finite values or cast to an integer typethat supports these values (e.g. 'Int64')

In [88]:
df.head()

   Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1   41.0    190.0   7.4     67     5    1  2010    67       S
1           2   36.0    118.0   8.0     72     5    2  2010    72       C
2           3   12.0    149.0  12.6     74     5    3  2010    74      PS
3           4   18.0    313.0  11.5     62     5    4  2010    62       S
4           5    NaN      NaN  14.3     56     5    5  2010    56       S

In [89]:
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler

In [91]:
df.values

array([[1, 41.0, 190.0, ..., 2010, 67, 'S'],
       [2, 36.0, 118.0, ..., 2010, 72, 'C'],
       [3, 12.0, 149.0, ..., 2010, 74, 'PS'],
       ...,
       [156, nan, 145.0, ..., 2010, 77, 'S'],
       [157, 14.0, 191.0, ..., 2010, 75, 'S'],
       [158, 18.0, 131.0, ..., 2010, 76, 'C']],
      shape=(158, 10), dtype=object)

In [92]:
array=df.values

In [93]:
array

array([[1, 41.0, 190.0, ..., 2010, 67, 'S'],
       [2, 36.0, 118.0, ..., 2010, 72, 'C'],
       [3, 12.0, 149.0, ..., 2010, 74, 'PS'],
       ...,
       [156, nan, 145.0, ..., 2010, 77, 'S'],
       [157, 14.0, 191.0, ..., 2010, 75, 'S'],
       [158, 18.0, 131.0, ..., 2010, 76, 'C']],
      shape=(158, 10), dtype=object)