In [2]:
import pandas as pd
df=pd.read_csv('data_clean.csv')
df.head()

   Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1   41.0    190.0   7.4     67     5    1  2010    67       S
1           2   36.0    118.0   8.0     72     5    2  2010    72       C
2           3   12.0    149.0  12.6     74     5    3  2010    74      PS
3           4   18.0    313.0  11.5     62     5    4  2010    62       S
4           5    NaN      NaN  14.3     56     5    5  2010    56       S

In [3]:
print(df.isnull().sum())

Unnamed: 0     0
Ozone         38
Solar.R        7
Wind           0
Temp C         0
Month          0
Day            0
Year           0
Temp           0
Weather        3
dtype: int64

In [4]:
print(df.isnull())

     Unnamed: 0  Ozone  Solar.R   Wind  Temp C  Month    Day   Year   Temp  \
0         False  False    False  False   False  False  False  False  False
1         False  False    False  False   False  False  False  False  False
2         False  False    False  False   False  False  False  False  False
3         False  False    False  False   False  False  False  False  False
4         False   True     True  False   False  False  False  False  False
..          ...    ...      ...    ...     ...    ...    ...    ...    ...
153       False  False    False  False   False  False  False  False  False
154       False  False    False  False   False  False  False  False  False
155       False   True    False  False   False  False  False  False  False
156       False  False    False  False   False  False  False  False  False
157       False  False    False  False   False  False  False  False  False

     Weather
0      False
1      False
2      False
3      False
4      False
..       ...
153    False
154    False
155    False
156    False
157    False

[158 rows x 10 columns]

In [6]:
median_ozone=df['Ozone'].median()
median_ozone

np.float64(30.5)

In [7]:
#df['Ozone'].fillna(median_ozone,inplace=True)
df.fillna({'Ozone': median_ozone}, inplace=True)

     Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0             1   41.0    190.0   7.4     67     5    1  2010    67       S
1             2   36.0    118.0   8.0     72     5    2  2010    72       C
2             3   12.0    149.0  12.6     74     5    3  2010    74      PS
3             4   18.0    313.0  11.5     62     5    4  2010    62       S
4             5   30.5      NaN  14.3     56     5    5  2010    56       S
..          ...    ...      ...   ...    ...   ...  ...   ...   ...     ...
153         154   41.0    190.0   7.4     67     5    1  2010    67       C
154         155   30.0    193.0   6.9     70     9   26  2010    70      PS
155         156   30.5    145.0  13.2     77     9   27  2010    77       S
156         157   14.0    191.0  14.3     75     9   28  2010    75       S
157         158   18.0    131.0   8.0     76     9   29  2010    76       C

[158 rows x 10 columns]

In [8]:
df.head()

   Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1   41.0    190.0   7.4     67     5    1  2010    67       S
1           2   36.0    118.0   8.0     72     5    2  2010    72       C
2           3   12.0    149.0  12.6     74     5    3  2010    74      PS
3           4   18.0    313.0  11.5     62     5    4  2010    62       S
4           5   30.5      NaN  14.3     56     5    5  2010    56       S

In [14]:
df['Solar.R'].isnull().sum()

np.int64(7)

In [9]:
median_solar=df['Solar.R'].median()
df.fillna({'Solar.R':median_solar},inplace=True)

     Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0             1   41.0    190.0   7.4     67     5    1  2010    67       S
1             2   36.0    118.0   8.0     72     5    2  2010    72       C
2             3   12.0    149.0  12.6     74     5    3  2010    74      PS
3             4   18.0    313.0  11.5     62     5    4  2010    62       S
4             5   30.5    197.0  14.3     56     5    5  2010    56       S
..          ...    ...      ...   ...    ...   ...  ...   ...   ...     ...
153         154   41.0    190.0   7.4     67     5    1  2010    67       C
154         155   30.0    193.0   6.9     70     9   26  2010    70      PS
155         156   30.5    145.0  13.2     77     9   27  2010    77       S
156         157   14.0    191.0  14.3     75     9   28  2010    75       S
157         158   18.0    131.0   8.0     76     9   29  2010    76       C

[158 rows x 10 columns]

In [12]:
df['Weather'].isna().sum()

np.int64(3)

In [11]:
weather_median=df['Weather'].mode()
df.fillna({'Weather':weather_median},inplace=True)

     Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0             1   41.0    190.0   7.4     67     5    1  2010    67       S
1             2   36.0    118.0   8.0     72     5    2  2010    72       C
2             3   12.0    149.0  12.6     74     5    3  2010    74      PS
3             4   18.0    313.0  11.5     62     5    4  2010    62       S
4             5   30.5    197.0  14.3     56     5    5  2010    56       S
..          ...    ...      ...   ...    ...   ...  ...   ...   ...     ...
153         154   41.0    190.0   7.4     67     5    1  2010    67       C
154         155   30.0    193.0   6.9     70     9   26  2010    70      PS
155         156   30.5    145.0  13.2     77     9   27  2010    77       S
156         157   14.0    191.0  14.3     75     9   28  2010    75       S
157         158   18.0    131.0   8.0     76     9   29  2010    76       C

[158 rows x 10 columns]

In [13]:
df['Temp'].isna().sum()

np.int64(0)

In [14]:
df.head(10)

   Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1   41.0    190.0   7.4     67     5    1  2010    67       S
1           2   36.0    118.0   8.0     72     5    2  2010    72       C
2           3   12.0    149.0  12.6     74     5    3  2010    74      PS
3           4   18.0    313.0  11.5     62     5    4  2010    62       S
4           5   30.5    197.0  14.3     56     5    5  2010    56       S
5           6   28.0    197.0  14.9     66     5    6  2010    66       C
6           7   23.0    299.0   8.6     65     5    7  2010    65      PS
7           8   19.0     99.0  13.8     59     5    8  2010    59       C
8           9    8.0     19.0  20.1     61     5    9  2010    61      PS
9          10   30.5    194.0   8.6     69     5   10  2010    69       S

In [17]:
weather_group=df.groupby('Weather')
print("The Average temperature on differnt weathers:-",weather_group['Temp'].mean())

Weather
C     77.734694
PS    76.872340
S     78.067797
Name: Temp, dtype: float64

In [19]:
month_group=df.groupby('Month')
print("The maximum speed of wind in each month:-\n",month_group['Wind'].max())

The maximum speed of wind in each month:-
 Month
5      20.1
6      20.7
7      14.9
8      15.5
9      16.6
May    12.0
Name: Wind, dtype: float64

In [20]:
#basically groupby function ka kaam ye hai ki kisi ek column ka gropu bnakr usko dusre colum ke hisaab se data analysis kr ske

In [21]:
print("The Value of ozone in each month:-\n",month_group['Ozone'].median())

The Value of ozone in each month:-
 Month
5      23.0
6      30.5
7      50.0
8      44.0
9      23.0
May    32.0
Name: Ozone, dtype: float64

In [24]:
df1=pd.read_csv('Salaries - Copy.csv')

In [25]:
df1.head(6)

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800
5  Prof          A   20       20  Male  122400

In [26]:
df1.tail()

         rank discipline  phd  service     sex  salary
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [28]:
rank_group=df1.groupby('rank')
rank_group.sum()

,discipline,phd,service,sex,salary
rank,,,,,
AssocProf,ABBABAABBBABB,196,147,MaleMaleMaleFemaleFemaleFemaleFemaleFemaleFema...,1193221
AsstProf,BBBBAABBBBBBAAABAAA,96,42,MaleMaleMaleMaleMaleMaleMaleMaleFemaleFemaleFe...,1545893
Prof,BAAABAAAABBBBBAAAABAABBABBBABABBBBBABAAAABBBAA,1245,985,MaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMa...,5686741

In [30]:
df1.groupby('rank').sum()

,discipline,phd,service,sex,salary
rank,,,,,
AssocProf,ABBABAABBBABB,196,147,MaleMaleMaleFemaleFemaleFemaleFemaleFemaleFema...,1193221
AsstProf,BBBBAABBBBBBAAABAAA,96,42,MaleMaleMaleMaleMaleMaleMaleMaleFemaleFemaleFe...,1545893
Prof,BAAABAAAABBBBBAAAABAABBABBBABABBBBBABAAAABBBAA,1245,985,MaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMa...,5686741

In [34]:
df1.groupby('rank')['salary'].sum()

rank
AssocProf    1193221
AsstProf     1545893
Prof         5686741
Name: salary, dtype: int64

In [31]:
print(df1.groupby('sex').max())

        rank discipline  phd  service  salary
sex
Female  Prof          B   39       36  161101
Male    Prof          B   56       51  186960

In [32]:
sorted_df = df.sort_values(by='Temp', ascending=False)
sorted_df

     Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
119         120   76.0    203.0   9.7     97     8   28  2010    97       S
121         122   84.0    237.0   6.3     96     8   30  2010    96       S
120         121  118.0    225.0   2.3     94     8   29  2010    94       S
122         123   85.0    188.0   6.3     94     8   31  2010    94       C
125         126   73.0    183.0   2.8     93     9    3  2010    93       C
..          ...    ...      ...   ...    ...   ...  ...   ...   ...     ...
25           26   30.5    266.0  14.9     58     5   26  2010    58       C
17           18    6.0     78.0  18.4     57     5   18  2010    57       C
26           27   30.5    197.0   8.0     57     5   27  2010    57      PS
24           25   30.5     66.0  16.6     57     5   25  2010    57      PS
4             5   30.5    197.0  14.3     56     5    5  2010    56       S

[158 rows x 10 columns]

In [33]:
sorted_solar = df.sort_values(by='Solar.R')
print(sorted_solar[['Solar.R']].head(3))

    Solar.R
81      7.0
20      8.0
27     13.0