In [1]:
import pandas as pd
import numpy as np

In [4]:
#pd.Series(data,index)
s=pd.Series(["Tanmay","Rahul"],[1,2])
print(s)

1    Tanmay
2     Rahul
dtype: str

In [6]:
Showroom=pd.Series([500000,710000,850000],["Swift","Alto","BMW"])
print(Showroom)

Swift    500000
Alto     710000
BMW      850000
dtype: int64

In [22]:
entries = {'swift': 649000,
           'santro': 391000,
           'audi': 5476000,
           'elantra': 1786000,
           'bolero': 1091000}
new_series=pd.Series(entries,name='price')
print(new_series)

swift       649000
santro      391000
audi       5476000
elantra    1786000
bolero     1091000
Name: price, dtype: int64

In [23]:
new_series[new_series > 1000000]

audi       5476000
elantra    1786000
bolero     1091000
Name: price, dtype: int64

In [24]:
new_series[new_series>1000000].index[0]

'audi'

In [25]:
new_series[new_series>1000000].index[1]
new_series[new_series>1000000].index[2]

'bolero'

In [29]:
new_series[new_series > 1000000].values[1]
#new_series[new_series > 1000000].values[2]

np.int64(1786000)

In [30]:
new_series[(new_series>1000000) & (new_series<2000000)]

elantra    1786000
bolero     1091000
Name: price, dtype: int64

In [ ]:
#Write code to print the names of the customers who have spent more than 300 rupees.

In [31]:
cust_names = ['Hemang', 'Farheen', 'Himadri', 'Monisha']
cust_bill = [256.78, 434.53, 109.25, 529.42]
cust_info = pd.Series(cust_bill, cust_names)

In [32]:
print(cust_info)

Hemang     256.78
Farheen    434.53
Himadri    109.25
Monisha    529.42
dtype: float64

In [35]:
print("The customers who has spent more than 300 rs")
cust_info[cust_info>300].index

The customers who has spent more than 300 rs

Index(['Farheen', 'Monisha'], dtype='str')

In [ ]:
#loc[]=>it is inclusive and not uses typical index no
#iloc[]=>it is exclusive and usies typical index number

In [36]:
entries_1 = {'swift': 649000,
           'santro': 391000,
           'audi': 5476000,
           'elantra': 1786000,
           'bolero': 1091000}
series_1=pd.Series(entries_1,name="price")
print(series_1)

swift       649000
santro      391000
audi       5476000
elantra    1786000
bolero     1091000
Name: price, dtype: int64

In [38]:
series_1.loc['swift']

swift    649000
Name: price, dtype: int64

In [40]:
print(series_1.loc[['swift']])
print(series_1.loc[['audi']])

swift    649000
Name: price, dtype: int64
audi    5476000
Name: price, dtype: int64

In [46]:

series_1.loc[['swift','elantra']]

swift       649000
elantra    1786000
Name: price, dtype: int64

In [45]:
#Slicing
series_1.loc['swift':'elantra']

swift       649000
santro      391000
audi       5476000
elantra    1786000
Name: price, dtype: int64

In [47]:
series_1.iloc[0]

np.int64(649000)

In [48]:
series_1.iloc[[0]]

swift    649000
Name: price, dtype: int64

In [49]:
series_1.iloc[0:5:1]

swift       649000
santro      391000
audi       5476000
elantra    1786000
bolero     1091000
Name: price, dtype: int64

In [50]:
cust_names = ['Mahesh', 'Farheen', 'Himadri', 'Monisha']
cust_bill = [256.78, 434.53, 109.25, 529.42]
cust_info = pd.Series(cust_bill, cust_names)

In [51]:
print(cust_info)

Mahesh     256.78
Farheen    434.53
Himadri    109.25
Monisha    529.42
dtype: float64

In [54]:
print(cust_info.loc[['Mahesh','Monisha']])

Mahesh     256.78
Monisha    529.42
dtype: float64

In [55]:
cust_info.loc[['Farheen','Himadri']]

Farheen    434.53
Himadri    109.25
dtype: float64

In [57]:
cust_info.loc['Mahesh':'Himadri']

Mahesh     256.78
Farheen    434.53
Himadri    109.25
dtype: float64

In [59]:
cust_info.iloc[0:4:3]

Mahesh     256.78
Monisha    529.42
dtype: float64

In [60]:
df_csv = pd.DataFrame({
    'Product': ['Soap', 'Shampoo', 'Toothpaste', 'Oil'],
    'Price': [30, 120, 45, 150],
    'Units_Sold': [100, 60, 80, 50]
})
df_csv

      Product  Price  Units_Sold
0        Soap     30         100
1     Shampoo    120          60
2  Toothpaste     45          80
3         Oil    150          50

In [61]:
df_csv.to_csv("retail.csv",index=False)
print("Succesful")

Succesful

In [62]:
sales_data=pd.read_csv("retail.csv")
sales_data

      Product  Price  Units_Sold
0        Soap     30         100
1     Shampoo    120          60
2  Toothpaste     45          80
3         Oil    150          50

In [63]:
print(sales_data)

      Product  Price  Units_Sold
0        Soap     30         100
1     Shampoo    120          60
2  Toothpaste     45          80
3         Oil    150          50

In [64]:
print(sales_data['Product'])

0          Soap
1       Shampoo
2    Toothpaste
3           Oil
Name: Product, dtype: str

In [65]:
print(sales_data['Units_Sold'])

0    100
1     60
2     80
3     50
Name: Units_Sold, dtype: int64

In [69]:
print(sales_data[['Product','Price']])

      Product  Price
0        Soap     30
1     Shampoo    120
2  Toothpaste     45
3         Oil    150

In [72]:
file_path="C:\\Users\\Tanmay\\Desktop\\PYTHON FINAL BOSS\\Pandas\\pharma_sales_data.csv"
df=pd.read_csv(file_path)
df

   Product_ID Product_Name      Category  Sales_Units  Revenue Region
0         101   PainRelief     Analgesic        500.0  25000.0  North
1         102   CoughSyrup  Cough & Cold        300.0  12000.0  South
2         103  AntibioticX    Antibiotic          NaN  40000.0   East
3         104     VitaminD    Supplement        700.0      NaN   West
4         105  DiabetesMed      Diabetes        450.0  31500.0  North
5         106      Antacid     Digestive          NaN  18000.0  South
6         107  AllergyPill       Allergy        600.0      NaN   East
7         108      FluShot       Vaccine        800.0  56000.0   West

In [73]:
df.head()

   Product_ID Product_Name      Category  Sales_Units  Revenue Region
0         101   PainRelief     Analgesic        500.0  25000.0  North
1         102   CoughSyrup  Cough & Cold        300.0  12000.0  South
2         103  AntibioticX    Antibiotic          NaN  40000.0   East
3         104     VitaminD    Supplement        700.0      NaN   West
4         105  DiabetesMed      Diabetes        450.0  31500.0  North

In [74]:
df.tail()

   Product_ID Product_Name    Category  Sales_Units  Revenue Region
3         104     VitaminD  Supplement        700.0      NaN   West
4         105  DiabetesMed    Diabetes        450.0  31500.0  North
5         106      Antacid   Digestive          NaN  18000.0  South
6         107  AllergyPill     Allergy        600.0      NaN   East
7         108      FluShot     Vaccine        800.0  56000.0   West

In [75]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_ID    8 non-null      int64
 1   Product_Name  8 non-null      str
 2   Category      8 non-null      str
 3   Sales_Units   6 non-null      float64
 4   Revenue       6 non-null      float64
 5   Region        8 non-null      str
dtypes: float64(2), int64(1), str(3)
memory usage: 699.0 bytes

In [76]:
df.describe()

       Product_ID  Sales_Units       Revenue
count     8.00000     6.000000      6.000000
mean    104.50000   558.333333  30416.666667
std       2.44949   180.046290  15938.684596
min     101.00000   300.000000  12000.000000
25%     102.75000   462.500000  19750.000000
50%     104.50000   550.000000  28250.000000
75%     106.25000   675.000000  37875.000000
max     108.00000   800.000000  56000.000000