In [2]:
import pandas as pd
df=pd.read_csv('encounters.csv')

In [3]:
df.head()

,Id,START,STOP,PATIENT,ORGANIZATION,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
0,32c84703-2481-49cd-d571-3899d5820253,2011-01-02T09:26:36Z,2011-01-02T12:58:36Z,3de74169-7f67-9304-91d4-757e0f3a14d2,d78e84ec-30aa-3bba-a33a-f29a3a454662,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,ambulatory,185347001,Encounter for problem (procedure),85.55,1018.02,0.00,NaN,NaN
1,c98059da-320a-c0a6-fced-c8815f3e3f39,2011-01-03T05:44:39Z,2011-01-03T06:01:42Z,d9ec2e44-32e9-9148-179a-1653348cc4e2,d78e84ec-30aa-3bba-a33a-f29a3a454662,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,outpatient,308335008,Patient encounter procedure,142.58,2619.36,0.00,NaN,NaN
2,4ad28a3a-2479-782b-f29c-d5b3f41a001e,2011-01-03T14:32:11Z,2011-01-03T14:47:11Z,73babadf-5b2b-fee7-189e-6f41ff213e01,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,outpatient,185349003,Encounter for check up (procedure),85.55,461.59,305.27,NaN,NaN
3,c3f4da61-e4b4-21d5-587a-fbc89943bc19,2011-01-03T16:24:45Z,2011-01-03T16:39:45Z,3b46a0b7-0f34-9b9a-c319-ace4a1f58c0b,d78e84ec-30aa-3bba-a33a-f29a3a454662,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,wellness,162673000,General examination of patient (procedure),136.80,1784.24,0.00,NaN,NaN
4,a9183b4f-2572-72ea-54c2-b3cd038b4be7,2011-01-03T17:36:53Z,2011-01-03T17:51:53Z,fa006887-d93c-d302-8b89-f3c25f88c0e1,d78e84ec-30aa-3bba-a33a-f29a3a454662,42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a,ambulatory,390906007,Follow-up encounter,85.55,234.72,0.00,55822004.0,Hyperlipidemia

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 27891 entries, 0 to 27890
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Id                   27891 non-null  str
 1   START                27891 non-null  str
 2   STOP                 27891 non-null  str
 3   PATIENT              27891 non-null  str
 4   ORGANIZATION         27891 non-null  str
 5   PAYER                27891 non-null  str
 6   ENCOUNTERCLASS       27891 non-null  str
 7   CODE                 27891 non-null  int64
 8   DESCRIPTION          27891 non-null  str
 9   BASE_ENCOUNTER_COST  27891 non-null  float64
 10  TOTAL_CLAIM_COST     27891 non-null  float64
 11  PAYER_COVERAGE       27891 non-null  float64
 12  REASONCODE           8350 non-null   float64
 13  REASONDESCRIPTION    8350 non-null   str
dtypes: float64(4), int64(1), str(9)
memory usage: 9.2 MB

In [5]:
possible_cols = ['Id', 'PATIENT', 'ENCOUNTERCLASS', 'BASE_ENCOUNTER_COST', 'PAYER', 'REASONDESCRIPTION']
possible_cols_lower = [c.lower() for c in possible_cols]

In [6]:
df.isnull().sum()

Id                         0
START                      0
STOP                       0
PATIENT                    0
ORGANIZATION               0
PAYER                      0
ENCOUNTERCLASS             0
CODE                       0
DESCRIPTION                0
BASE_ENCOUNTER_COST        0
TOTAL_CLAIM_COST           0
PAYER_COVERAGE             0
REASONCODE             19541
REASONDESCRIPTION      19541
dtype: int64

In [7]:
df.dropna(subset=['REASONDESCRIPTION'], inplace=True)
print("\nAfter handling missing values:")
df.head()

After handling missing values:

,Id,START,STOP,PATIENT,ORGANIZATION,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
4,a9183b4f-2572-72ea-54c2-b3cd038b4be7,2011-01-03T17:36:53Z,2011-01-03T17:51:53Z,fa006887-d93c-d302-8b89-f3c25f88c0e1,d78e84ec-30aa-3bba-a33a-f29a3a454662,42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a,ambulatory,390906007,Follow-up encounter,85.55,234.72,0.00,55822004.0,Hyperlipidemia
7,2cfd4ddd-ad13-fe1e-528b-15051cea2ec3,2011-01-04T14:49:55Z,2011-01-04T15:04:55Z,d856d6e6-4c98-e7a2-129b-44076c63d008,d78e84ec-30aa-3bba-a33a-f29a3a454662,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,ambulatory,185347001,Encounter for problem,85.55,11855.19,11205.43,363406005.0,Malignant tumor of colon
9,17966936-0878-f4db-128b-a43ae10d0878,2011-01-05T04:02:09Z,2011-01-05T04:17:09Z,bc9d59c3-0a30-6e3b-f47d-022e4f03c8de,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,outpatient,185347001,Encounter for problem,85.55,9881.17,7872.94,254637007.0,Non-small cell lung cancer (disorder)
14,4b6a38e6-7df9-2d75-d850-6bd662f3d05b,2011-01-07T21:02:09Z,2011-01-07T22:39:45Z,bc9d59c3-0a30-6e3b-f47d-022e4f03c8de,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,outpatient,185347001,Encounter for problem,85.55,5136.00,4076.80,424132000.0,Non-small cell carcinoma of lung TNM stage 1 ...
16,f39e72a6-a58e-0aea-cc1f-8aee6f126cc0,2011-01-08T15:20:55Z,2011-01-08T15:35:55Z,88986fec-6364-262e-37d4-e20ceb511166,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,ambulatory,390906007,Follow-up encounter,85.55,234.72,155.77,55822004.0,Hyperlipidemia

In [9]:
df.isnull().sum()

Id                     0
START                  0
STOP                   0
PATIENT                0
ORGANIZATION           0
PAYER                  0
ENCOUNTERCLASS         0
CODE                   0
DESCRIPTION            0
BASE_ENCOUNTER_COST    0
TOTAL_CLAIM_COST       0
PAYER_COVERAGE         0
REASONCODE             0
REASONDESCRIPTION      0
dtype: int64

In [10]:
df.head()

,Id,START,STOP,PATIENT,ORGANIZATION,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
4,a9183b4f-2572-72ea-54c2-b3cd038b4be7,2011-01-03T17:36:53Z,2011-01-03T17:51:53Z,fa006887-d93c-d302-8b89-f3c25f88c0e1,d78e84ec-30aa-3bba-a33a-f29a3a454662,42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a,ambulatory,390906007,Follow-up encounter,85.55,234.72,0.00,55822004.0,Hyperlipidemia
7,2cfd4ddd-ad13-fe1e-528b-15051cea2ec3,2011-01-04T14:49:55Z,2011-01-04T15:04:55Z,d856d6e6-4c98-e7a2-129b-44076c63d008,d78e84ec-30aa-3bba-a33a-f29a3a454662,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,ambulatory,185347001,Encounter for problem,85.55,11855.19,11205.43,363406005.0,Malignant tumor of colon
9,17966936-0878-f4db-128b-a43ae10d0878,2011-01-05T04:02:09Z,2011-01-05T04:17:09Z,bc9d59c3-0a30-6e3b-f47d-022e4f03c8de,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,outpatient,185347001,Encounter for problem,85.55,9881.17,7872.94,254637007.0,Non-small cell lung cancer (disorder)
14,4b6a38e6-7df9-2d75-d850-6bd662f3d05b,2011-01-07T21:02:09Z,2011-01-07T22:39:45Z,bc9d59c3-0a30-6e3b-f47d-022e4f03c8de,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,outpatient,185347001,Encounter for problem,85.55,5136.00,4076.80,424132000.0,Non-small cell carcinoma of lung TNM stage 1 ...
16,f39e72a6-a58e-0aea-cc1f-8aee6f126cc0,2011-01-08T15:20:55Z,2011-01-08T15:35:55Z,88986fec-6364-262e-37d4-e20ceb511166,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,ambulatory,390906007,Follow-up encounter,85.55,234.72,155.77,55822004.0,Hyperlipidemia

In [13]:
avg_cost=df.groupby('ENCOUNTERCLASS')['BASE_ENCOUNTER_COST'].mean()
print(avg_cost)

ENCOUNTERCLASS
ambulatory    110.034084
emergency     139.201323
inpatient     135.808129
outpatient     85.550000
wellness      136.800000
Name: BASE_ENCOUNTER_COST, dtype: float64

In [14]:
total_claim=df.groupby('PAYER')['TOTAL_CLAIM_COST'].sum()
print("Total claim cost by payer:-")
total_claim

Total claim cost by payer:-

PAYER
047f6ec3-6215-35eb-9608-f9dda363a44c    1195513.62
42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a    1700220.24
4d71f845-a6a9-3c39-b242-14d25ef86a8d    1091943.15
5059a55e-5d6e-34d1-b6cb-d83d16e57bcf    1051841.75
6e2f1a2d-27bd-3701-8d08-dae202c58632    1623290.20
7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a    7165889.64
7caa7254-5050-3b5e-9eae-bd5ea30e809c    2828182.83
b1c428d6-4f07-31e0-90f0-68ffa6ff8c76    9983932.33
b3221cfc-24fb-339e-823d-bc4136cbc4ed     534523.99
d47b3510-2895-3b70-9897-342d681c769d    1354417.07
Name: TOTAL_CLAIM_COST, dtype: float64

In [16]:
sorted_df = df.sort_values(by='BASE_ENCOUNTER_COST', ascending=True)
#sorted_df = df.sort_values(by='BASE_ENCOUNTER_COST', ascending=False)
sorted_df

,Id,START,STOP,PATIENT,ORGANIZATION,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
99,632c4faa-e7fc-7288-a34d-021a26340759,2011-02-06T07:47:14Z,2011-02-06T08:02:14Z,905d0433-9ca3-4883-cbd4-3df36fd5f1c6,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,ambulatory,390906007,Follow-up encounter,85.55,234.72,155.77,55822004.0,Hyperlipidemia
58,0e06fd4f-0c37-39b0-d76f-1743753bcae0,2011-01-21T23:56:20Z,2011-01-22T00:11:20Z,54889029-0a1e-0b75-5980-1c091dd4bc0e,d78e84ec-30aa-3bba-a33a-f29a3a454662,4d71f845-a6a9-3c39-b242-14d25ef86a8d,ambulatory,390906007,Follow-up encounter,85.55,234.72,0.00,55822004.0,Hyperlipidemia
47,fa03ab26-73ae-7097-d802-f114934ee1bc,2011-01-19T16:22:13Z,2011-01-19T16:37:13Z,e3eeac06-7f9d-8e95-5cce-2dea6641f469,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,ambulatory,316744009,Office Visit,85.55,85.55,36.44,26929004.0,Alzheimer's disease (disorder)
46,cffe517b-7347-fa76-355f-20d92e056275,2011-01-18T20:38:53Z,2011-01-18T20:53:53Z,470e7dd9-9788-57f6-ee81-1e9acb075c1c,d78e84ec-30aa-3bba-a33a-f29a3a454662,4d71f845-a6a9-3c39-b242-14d25ef86a8d,ambulatory,185345009,Encounter for symptom,85.55,3952.18,0.00,10509002.0,Acute bronchitis (disorder)
37,4a11829f-afdb-3115-0708-8adc1dbac1cb,2011-01-16T03:40:00Z,2011-01-16T03:56:16Z,a6dc36b3-0ac3-48b1-3088-707e8871a914,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,ambulatory,185345009,Encounter for symptom,85.55,500.55,366.30,10509002.0,Acute bronchitis (disorder)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3495,4aa73785-372c-487d-d886-759a5b9749ad,2013-01-10T22:19:27Z,2013-01-11T22:19:27Z,18e7819f-5407-9d84-de9f-27a4d5526695,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,inpatient,410410006,Screening surveillance (regime/therapy),146.18,269.21,183.37,254837009.0,Malignant neoplasm of breast (disorder)
12697,87f4b01e-6119-31fc-9a68-7a737fa058e1,2016-03-02T17:21:39Z,2016-03-02T18:21:39Z,64903644-0d39-d9d1-b1d4-9da14ae1fe61,d78e84ec-30aa-3bba-a33a-f29a3a454662,6e2f1a2d-27bd-3701-8d08-dae202c58632,emergency,183478001,Emergency hospital admission for asthma,146.18,146.18,36.19,195967001.0,Asthma
15947,c88ecc4c-d9a0-aeef-2f40-62bd8012cdda,2017-07-06T09:39:29Z,2017-07-06T10:39:29Z,ee96d0b5-a76a-6801-3112-b02b9b2f748e,d78e84ec-30aa-3bba-a33a-f29a3a454662,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,emergency,50849002,Emergency Room Admission,146.18,146.18,0.00,55680006.0,Drug overdose
15949,364a3036-0e30-1b46-04da-fb36ea9314b9,2017-07-06T12:07:03Z,2017-07-07T12:07:03Z,be66cdbe-0379-ab61-5cd4-13c45362895b,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,inpatient,410410006,Screening surveillance (regime/therapy),146.18,290.18,200.14,254837009.0,Malignant neoplasm of breast (disorder)
91,841b4cb6-5d89-1091-9a90-11df4e7b14cc,2011-02-03T22:06:01Z,2011-02-04T22:06:01Z,63ebbeb6-3160-da00-76a3-11888839703a,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,inpatient,305336008,Admission to hospice (procedure),146.18,0.00,0.00,26929004.0,Alzheimer's disease (disorder)

In [17]:
sorted_df[['Id', 'BASE_ENCOUNTER_COST']].head()

                                      Id  BASE_ENCOUNTER_COST
99  632c4faa-e7fc-7288-a34d-021a26340759                85.55
58  0e06fd4f-0c37-39b0-d76f-1743753bcae0                85.55
47  fa03ab26-73ae-7097-d802-f114934ee1bc                85.55
46  cffe517b-7347-fa76-355f-20d92e056275                85.55
37  4a11829f-afdb-3115-0708-8adc1dbac1cb                85.55